#pragma kernel NoiseGen
#pragma kernel SliceTexture

Texture3D<float4> voxels;
RWTexture2D<float4> result;
 int layer;
 
RWTexture2D<float4> Noise1;


[numthreads(8,8,1)]
void NoiseGen(uint3 id : SV_DispatchThreadID)
{
    Noise1[id.xy] = float4(0, 1, 0, 1);
}

[numthreads(8,8,8)]
void SliceTexture(uint3 id : SV_DispatchThreadID)
{
    uint3 pos = uint3(id.x, id.y, layer);
    result[id.xy] = voxels[pos];
}